version: '3.5'
services:
  cotizaciones:
      build:
        context: .
        dockerfile: Dockerfile
      image: docker.pkg.github.com/daka22/cotizaciones/cotizacion:latest
      container_name: cotizaciones
      restart: always
      networks:
          - proxy
          - red_interna
networks:
    red_interna:
        driver: bridge
    proxy:
        driver: bridge
        name: proxy
        external: true
